using BlazorBootstrap;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage;
using Zenith.Models.Account;
using Zenith.Models.QuestionModels;
namespace ZenithFrontEnd.Components.Pages.Dashboard;

public partial class StudentDashboard : ComponentBase
{
    
    //these are the properties required for the graph to be duisplayed 
    private LineChart lineChart = default!;
    private LineChartOptions lineChartOptions = default!;
    private ChartData chartData = default!;
    
    //will make sure the page does not try to redner without the required information first, prevenmting a null exception being thrown 
    public bool FinishedRendering = false;
    
    //stores the most recent stat so they cna be displayed in more detial 
    WeeklySummary MostRecentStats {get; set;}
    
    //stores every collection of long terms stats
    private IEnumerable<WeeklySummary>? Summaries { get; set; }
    //stores all of the recently answered rounds of questioning 
    private List<CompletedRoundOfQuestioning>? QuestioningRounds { get; set; }
    //stores the round of questioning the user would like to see in more detial 
    private IEnumerable<QuestionModels.AnsweredQuestion> CurrentQuestioningRound {get; set;}
    //tracks whether to open the window that will track the most recent round of quesitoning
    private bool displayQuestionRound = false;
    private bool authenticated = false;
    
    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        //the code will not need to be run after the firts render as all data has been assigned already
        if (!firstRender)
        {
            return;
        }

        string? Id = await GetId();
        if (Id == null)
        {
            authenticated = false;
            return;
        }
        authenticated = true;
        
        //getting all the longterm statistics from the API
        string weeklySummariesAddress = "http://localhost:5148/api/Questions/GetAllweeklySummarys/" + Id;
        HttpResponseMessage summariesResponse = await Http.GetAsync(weeklySummariesAddress);
        Summaries = await summariesResponse.Content.ReadFromJsonAsync<IEnumerable<WeeklySummary>>();
        
        //getting all of the recent question rounds from API 
        string questioningRoundsAddress = "http://localhost:5148/api/Questions/GetAllQuestioningRounds/" + Id;
        HttpResponseMessage questionRoundsResponse = await Http.GetAsync(questioningRoundsAddress);
        QuestioningRounds = await questionRoundsResponse.Content.ReadFromJsonAsync<List<CompletedRoundOfQuestioning>>();

        //asinging the most recvent stats
        MostRecentStats = Summaries.Last();
        
        InitialiseGraph();
        
        await lineChart.InitializeAsync(chartData, lineChartOptions);
        StateHasChanged();
    }

    //generated by blazor bootstrap so the graph can be created 
    private void InitialiseGraph()
    {
        var colors = ColorUtility.CategoricalTwelveColors;

        List<string> labels = new List<string>();
        List<double?> data = new List<double?>();
        foreach (WeeklySummary summary in Summaries)
        {
            
            labels.Add(summary.weekNumber);
            data.Add(summary.completion);

        }
        
        var datasets = new List<IChartDataset>();
        
        
        
        var dataset1 = new LineChartDataset
        {
            Label = "Completion",
            Data = data, 
            BackgroundColor = colors[0],
            BorderColor = colors[0],
            BorderWidth = 2,
            HoverBorderWidth = 4,
            // PointBackgroundColor = colors[0],
            // PointRadius = 0, // hide points
            // PointHoverRadius = 4,
        };
        datasets.Add(dataset1);
        chartData = new ChartData { Labels = labels, Datasets = datasets };

        lineChartOptions = new();
        lineChartOptions.Responsive = true;
        lineChartOptions.Interaction = new Interaction { Mode = InteractionMode.Index };

        lineChartOptions.Scales.X!.Title = new ChartAxesTitle { Text = "Weeks", Display = true };
        lineChartOptions.Scales.Y!.Title = new ChartAxesTitle { Text = "Completion", Display = true };
        lineChartOptions.Scales.Y.Max = 1.0;
        lineChartOptions.Scales.Y.Min = 0.0;
        
        FinishedRendering = true;
        
        
    }

    //when a user wnats to see a round of questioning they have completed this will open the window so they can view it
    private void DisplayRoundOfQuestioning(int roundIndex)
    {
        CurrentQuestioningRound = QuestioningRounds[roundIndex].answeredQuestions;
        displayQuestionRound = true;
        
        StateHasChanged();
    }

    private void NavigateToSelection()
    {
        NavigationManager.NavigateTo($"/QuestionSelection");
    }

    //closes the question round viewing window when the user is done looking at a round of questions
    private void Close()
    {
        displayQuestionRound = false;
        StateHasChanged();
    }
    
    private async Task<string?> GetId()
    {
        ProtectedBrowserStorageResult<string?> Id = await SessionStorage.GetAsync<string>("Id");
        if (Id.Success)
        {
            return Id.Value;
        }
        
        return null;
    }
    
}